version: "3"
services:
  jobboard:
    container_name: league
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - MONGODB_DATABASE_URL=mongodb://mongodb:27017/league
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
    command: ["air"]
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo
    container_name: mongodb345
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db  # Persist MongoDB data\
  redis:
    image: redis 
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data/db

